spring.application.name=EmployeeCrudApplication
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/employeedb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Pass@123

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=neck-synchronous-sneeze-80574.db.redis.io
spring.data.redis.port=18518
spring.data.redis.password=wt4nRfzoNBoq5CS5i7wmPpufHzxcnO4l
spring.data.redis.ssl.enabled=false